[[tools]]
type = "LogitLens"
name = "logit-lens"

[[tools]]
type = "ConceptLens"
name = "concept-lens"
n_predictions = 5

    [[tools.models]]
    model_name = "meta-llama/Llama-2-7b-hf"
    n_concept_heads = 80

    [tools.models.data_paths]
    concept_heads = "concept-heads/llama-2-7b-hf.json"

    [[tools.models]]
    model_name = "meta-llama/Llama-3.1-8B"
    n_concept_heads = 50

    [tools.models.data_paths]
    concept_heads = "concept-heads/llama-3-1-8B.json"


[[tools]]
type = "ActivationPatching"
name = "activation-patching"